# this workflow will build the production files for deployment and upload as artefact
name: build production files

on: 
  push: 
    branches: main
  workflow_dispatch:

jobs: 
  build: 
    name: Build dist
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload Prod-ready files
        uses: actions/upload-artifact@v3
        with: 
          name: dist-files
          path: ./dist
