# thiw workflow will run e2e tests with cypress

name: Automated e2e testing

on:
  pull_request:
  workflow_dispatch:
  
env: 

  USER_NAME: ${{secrets.USER_NAME}}
  USER_EMAIL: ${{secrets.USER_EMAIL}}
  USER_PASSWORD: ${{secrets.USER_PASSWORD}}
  USER_TOKEN: ${{secrets.USER_TOKEN}}
  
jobs: 
  run-e2e-tests:
    name: Run e2e test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Cypress.io
        uses: cypress-io/github-action@v4
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm run dev
          
          # Records to Cypress Cloud
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
